version: '3'

services:
    backend:
        build: 'backend'
        ports:
            - '8000:8000'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - postgres
    frontend:
        build: 'frontend'
        ports:
            - '18267:18267'
        depends_on:
            - backend
    postgres:
        build: 'postgres'
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql

volumes:
    build_folder:
